# Generated by Django 4.0.5 on 2022-06-11 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='skills',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.skill'),
        ),
    ]
