# Generated by Django 4.0.5 on 2022-06-11 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_race_character_race_character_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='attributes',
        ),
        migrations.AddField(
            model_name='character',
            name='attributes',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.attribute'),
        ),
    ]
